# -*- coding: utf-8 -*-
"""Lab 1 - Iker Leal ; Amanda Pérez ; Augusto Calfani ; Eduard Raymundo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BYI_dGqvcriA674Ys7HPFZsCV0ArF359

**Grupo:** Iker Leal ; Amanda Pérez ; Augusto Calfani ; Eduard Raymundo

**Breve explicación. Ejercicio 1: Implementar nuevas operaciones**

El código define una función llamada `nuevas_op` que recibe como parámetros un `alfabeto` y una `palabra`. La función analiza la palabra para determinar si sus símbolos pertenecen al alfabeto dado, recorriendo cada carácter por medio de un `for` y verificando si se encuentra dentro de la lista de símbolos permitidos.

Por otra parte, cuenta cuántas veces aparecen las letras *"a"* y *"b"* dentro de la palabra mediante `contadores` que se incrementan cada vez que se encuentra uno de esos caracteres.

Por último, la función ordena las letras de la palabra alfabéticamente utilizando la función `sorted`, que devuelve los caracteres ordenados, y `join`, que los vuelve a unir en una cadena.

Por último, devuelve un texto con los resultados obtenidos.
"""

#EJERCICIO 1
def nuevas_op(alfabeto, palabra):

  #Verificar si una palabra pertenece al alfabeto.
    for i in range(len(palabra)):
        if palabra[i] not in alfabeto:
            x = False
        else:
            x = True

  #Contar cuántas veces aparece cada símbolo en la palabra.
    contadorA = 0
    contadorB = 0
    for letra in palabra:
        if letra == "a":
            contadorA += 1
        elif letra == "b":
            contadorB += 1
        else:
            print("Hay un símbolo no perteneciente al alfabeto")

  #Ordenar la palabra alfabéticamente.
    palabra_ordenada = "".join(sorted(palabra))
    return f"Pertenece al alfabeto?: {x} \nCantidad de As: {contadorA} \nCantidad de Bs: {contadorB} \nPalabra ordenada: '{palabra_ordenada}'"


alfabeto = ['a', 'b']
palabra = "abbaba"
print(nuevas_op(alfabeto,palabra))

"""**Breve explicación. Ejercicio 2: Definir un nuevo lenguaje.**

La modificación se realiza en la función `pertenece_L1`, que ahora verifica que la cantidad de letras *"b"* en una palabra sea **impar**. Para ello se utiliza `palabra.count('b') % 2 == 1`, que cuenta cuántas *"b"*  hay y usa el operador módulo para comprobar si el número es impar. De esta forma, al generar el lenguaje solo se seleccionan las palabras que cumplen con esta nueva regla.
"""

#EJERCICIO 2
from itertools import product

def generar_palabras(alfabeto, tamaño):
    return [''.join(p) for i in range(tamaño+1) for p in product(alfabeto, repeat=i)]

#Función que genera palabras que tienen una cantidad impar de 'b'.
def pertenece_L1(palabra):
    return palabra.count('b') % 2 == 1  # Número impar de 'b's

def generar_lenguaje(alfabeto, tamaño, criterio):
    palabras = generar_palabras(alfabeto, tamaño)
    return [p for p in palabras if criterio(p)]

# Ejemplo de uso
alfabeto = {'a', 'b'}
tamaño = 4

L1 = generar_lenguaje(alfabeto, tamaño, pertenece_L1)
print("L1:", L1)

"""**Breve explicación. Ejercicio 3: Implementar una nueva gramática.**

Se modificó la regla recursiva para que, a partir de cada palabra generada previamente, se agregue una *"a"* y una *"b"*. De esta forma, la función construye nuevas palabras combinando ambos símbolos en cualquier orden. Así, la gramática genera todas las combinaciones posibles de *"a"* y *"b"* hasta la longitud indicada.
"""

#EJERCICIO 3
def generar_gramatica(n):
    if n == 0:
        return [""]

    palabra = []
    palabras_menores = generar_gramatica(n - 1)

    for p in palabras_menores:
        palabra.append(p + "a")
        palabra.append(p + "b")
    return palabra

# Ejemplo de uso
n = 3
palabras = generar_gramatica(n)
print(palabras)  #['aaabbb']